[staging_routers]
10.0.0.100

[all:vars]
# Standard connection variables
ansible_user=john
ansible_password=password
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group14-sha1 -o HostKeyAlgorithms=+ssh-rsa'

